#pragma config(Sensor, in4,    middleLine,     sensorLineFollower)
#pragma config(Sensor, in5,    rightLine,      sensorLineFollower)
#pragma config(Sensor, in6,    leftLine,       sensorLineFollower)
#pragma config(Sensor, in7,    lightSensor,    sensorReflection)
#pragma config(Sensor, in8,    petentiometer,  sensorPotentiometer)
#pragma config(Sensor, dgtl1,  sonar,          sensorSONAR_cm)
#pragma config(Sensor, dgtl3,  frontTouch,     sensorTouch)
#pragma config(Sensor, dgtl4,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl8,  clawTouch,      sensorTouch)
#pragma config(Motor,  port2,           leftMotor,     tmotorVex269, openLoop, reversed)
#pragma config(Motor,  port3,           rightMotor,    tmotorVex269, openLoop)
#pragma config(Motor,  port6,           clawMotor,     tmotorVex269, openLoop)
#pragma config(Motor,  port7,           armMotor,      tmotorVex269, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                                         			- peeptest -          			                            *|
|*                                      												                                      *|
|*								 The robot drives .5m forwards and then backwards the same distance			          	*|
|* 						 		and repeats, adding .5m, until it reaches 2.5m. The robot learns to									*|
|*										move completely straight, using the right and left encoders											*|
|*  																																																	*|
|*																																																		*|
|*																					Wheel: 10.5cm																							*|
|*																					Circumference:																						*|
|*														    	pi*diameter = pi*10.5 = 32.98 ~ 33 																*|
|*																				50:33 = 1.5*360 = 540																				*|
|*																																																		*|
|*																																																		*|
|*																																																		*|
|*																																																		*|
\*-----------------------------------------------------------------------------------------------4246-*/
#include "../../includes/headers/myheader.h"
#include "../../includes/functions/motorFunctions.inc"

//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++


task main()
{
	resetEncoder();
	wait1Msec(2000);
	int counter;

	for(counter = 1; counter <= 5; counter++){
			resetEncoder();
			driveEncoder(BASEDIST*counter, true);
			resetEncoder();
			driveEncoder(BASEDIST*counter, false);
			resetEncoder();
	}




}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
